### ISSUE TITLE
✍ animation example

### ISSUE THREAD

**Issue by yjkwon07** [yjkwon07/CMS#2]
[[ Loading animation ] animation 속성활용 로딩 애니메이션 만들기](https://www.youtube.com/watch?v=3QTTHLcDjaE&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=37)

<details>
    <summary>dot animation</summary>

```css
.dot_one { animation: dot_one 2s infinite; }
.dot_two { animation: dot_two 2s infinite; }
.dot_three { animation: dot_three 2s infinite; }

@keyframes dot_one {
  0% { opacity: 0; }
  15% { opacity: 0; }
  25% { opacity: 1; }
  100% { opacity: 1; }
}
@keyframes dot_two {
  0% { opacity: 0; }
  40% { opacity: 0; }
  50% { opacity: 1; }
  100% { opacity: 1; }
}
@keyframes dot_three {
  0% { opacity: 0; }
  65% { opacity: 0; }
  75% { opacity: 1; }
  100% { opacity: 1; }
}
```
</details>

<details>
    <summary>bouncing_ball animation</summary>

```css

.bouncing_ball {
  position: relative;
  width: 4rem;
  margin: 0 auto;
  height: 12rem;
  border: 1px solid #fff;
}

.ball {
  width: 4rem;
  height: 4rem;
  background: #fff;
  border-radius: 50%;
  position: absolute;
  animation: bounce 1s infinite;
}

@keyframes bounce {
  0%  { top: 0; animation-timing-function: ease-in; }
  34% { transform: scale(1, 1); }
  35% { top: 8rem; animation-timing-function: ease-out; transform: scale(1.3, 0.7); }
  45% { transform: scale(1, 1); }
  100% { top: 0; }
}
```
</details>

[[ Loading animation 2 ] animation 속성활용 로딩 애니메이션 만들기 - CSS Loading Animation](https://www.youtube.com/watch?v=P_4eO65g0ac&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=38)

<details>
    <summary>bouncing_ball animation</summary>

```css

.spinner {
  position: relative;
  width: 6rem;
  height: 6rem;
  margin: 6rem auto;
  border: 1px solid #fff;
}

div[class^="curve"] {
  position: absolute;
  transform: rotate(135deg);
  animation: spin 4s infinite;
}

@keyframes spin {
  0% { transform: rotate(135deg); opacity: 1;}
  25% { opacity: 0.75;}
  50% { transform: rotate(675deg); opacity: 1;}
  75% { opacity: 0.75;}
  100% { transform: rotate(135deg); opacity: 1;}
}

.curve_top_left {
  width: 3rem;
  height: 3rem;
  border-top: 0.5rem solid #fff;
  border-left: 0.5rem solid #fff;
  border-top-left-radius: 100%;
  transform-origin: 100% 100%; // 기준점 조정
}

.curve_top_right {
  width: 2rem;
  height: 2rem;
  top: 1rem;
  right: 1rem;
  border-right: 0.5rem solid #fff;
  border-top: 0.5rem solid #fff;
  border-top-right-radius: 100%;
  transform-origin: 0 100%;
}

.curve_bottom_right {
  width: 3rem;
  height: 3rem;
  bottom: 0;
  right: 0;
  border-bottom: 0.5rem solid #fff;
  border-right: 0.5rem solid #fff;
  border-bottom-right-radius: 100%;
  transform-origin: 0 0;
}

.curve_bottom_left {
  width: 2rem;
  height: 2rem;
  left: 1rem;
  bottom: 1rem;
  border-left: 0.5rem solid #fff;
  border-bottom: 0.5rem solid #fff;
  border-bottom-right-radius: 100%;
  transform-origin: 100% 0;
}

.center_circle {
   width: 1.5rem;
   height: 1.5rem;
   position: absoulte;
   left: 50%; top: 50%;
   background: #fff;
   border-radius: 50%;
   transform:translate(-50%, -50%);
}

```
</details>

[[ Link Animation ] 평범한 링크를 재밌는 애니메이션으로 구현하기](https://www.youtube.com/watch?v=UvT6hHjH07k&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=39)

<details>
    <summary>before selector slide text</summary>

```css

a.fade_in_bg {
  text-decoration: none;
  border-bottom: 0.0625rem dotted #3498db;
  padding: 0 0.25em 0.05em;
}

a.fade_in_bg:hover {
  background: #3r98db;
  color: #fff;
}

a[class^="slide"] {
  text-decoration: none;
  line-height: 1.5em;
  padding: 0 0.25em;
  border-bottom: 0.0625em dotted #3498db;
  position: relative;
  overflow: hidden;
  display: inline-block; // 자기 크기를 모르기 때문에 overflow효과를 적용하지 못해 block을 적용
  vertical-align: bottom; // 요소 크기 위치 맞춤
}

a[class^="slide"]:before {
  position: absolute;
  content: attr(data-linktext);
  background: #3498db;
  color: #fff;
  transition: 0.35s;
}

.slide_from_left:before {
  left: -100%;
  right: 100%;
}

a[class^="slide"]:hover:before {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}

.slide_from_right:before {
  left: 100%;
  right: -100%;
}

.slide_from_top:before {
  top: -100%;
  bottom: 100%;
  left: 0;
  right: 0;
}

.slide_from_bottom:before {
  top: 100%;
  bottom: -100%;
  left: 0;
  right: 0;
}

a.fade_in_underline {
  text-decoration: none;
  padding: 0 0.125em 0.05em;
  border-bottom: 0.125em solid transparent;
  transition: all 0.35s;
}

a.fade_in_underline:hover {
  border-color: #3498db;
}

a[class^="underline"] {
  text-decoration: none;
  padding: 0 0.125em 0.05em;
  position: relative;
}

a[class^="underline"]:before {
  content: '';
  position: absolute;
  top: 100%;
  border-bottom: 0.125em solid #3498db;
  transition: 0.35s;
}

.underline_from_left:before {
  left: 0;
  right: 100%
}

.underline_from_right:before {
  left: 100%;
  right: 0;
}

.underline_from_center:before {
  left: 50%;
  right: 50%;
}

a[class^="underline"]:hover:before {
  left: 0;
  right: 0;
}


```
</details>

[[ button Animation ] 평범한 버튼에 재밌는 애니메이션 구현하기](https://www.youtube.com/watch?v=JFlfv07PttQ&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=40)

<details>
    <summary>before selector slide text animation</summary>

```css

button {
  font-size: 2em;
  background: #3498db;
  color: #fff;
  border: 0.25rem solid #3498db;
  padding: 0.85em 0.75em;
  margin: 1rem;
  position: relative;
  overflow: hidden;
  z-index: 1; /* background 분리 */
  /*  | (contents)  | (background) */
}

button:hover {
  color: #3498db;
}

button:before {
  content: '';
  background: #ecf0f1;
  position: absolute;
  padding: 0.85em 0.75em;
  z-index: -1;
  /*  | (contents)  | (before) | (background) 이 부분은 before, after에만 적용되는 z-index 효과 */
}

button[class^="slide"]:before {
  transition: 0.35s;
}

button[class^="slide"]:hover:before {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}

.slide_from_left:before {
  left: -100%;
  right: 100%;
  top: 0;
  bottom: 0;
}

.slide_from_right:before {
  left: 100%;
  right: -100%;
  top: 0;
  bottom: 0;
}

.slide_from_top:before {
  left: 0;
  right: 0;
  top: -100%;
  bottom: 100%;
}

.slide_from_bottom:before {
  left: 0;
  right: 0;
  top: 100%;
  bottom: -100%;
}

.grow_box:before {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0);
}

.grow_box:hover:before {
  transform: scale(1);
}

.grow_ellipse:before {
  left: -50%;
  right: -50%;
  top: -50%;
  bottom: -50%;
  border-radius: 50%;
  transform: scale(0);
  transition: 0.35s;
}

.grow_ellipse:hover:before {
  transform: scale(1);
}

.grow_skew_forward:before {
  left: -20%; // 크기 확장
  right: -20%; // 크기 확장
  top: 0;
  bottom: 0;
  transform: skewX(-45deg) scaleX(0);
  transition: 0.35s;
}

.grow_skew_forward:hover:before {
  transform: skewX(-45deg) scaleX(1);
}

.grow_skew_backward:before {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(45deg) scaleX(0);
  transition: 0.35s;
}

.grow_skew_backward:hover:before {
  transform: skewX(45deg) scaleX(1);
}

.grow_spin:before {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0) rotate(-180deg);
  transition: 0.35s;
}

.grow_spin:hover:before {
  transform: scale(1) rotate(0);
}

```
</details>

[[ Nav Style - part1 ] 반응형 메뉴 스타일 구현하기(pc, 태블릿 구간) - flex, fontawesome, 반응형, 클릭 메뉴 구현](https://www.youtube.com/watch?v=-jmFMOZeZX0&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=45)

<details>
    <summary>before selector slide box animation</summary>

```css
.wrapper {
  max-width: 60rem;
  width: 100%;
  margin: 5rem auto;
  position: relative;
}

a {
  text-decoration: none;
}

nav {
  display: flex;
  justify-content: center;
  font-size: 1.2em;
}

.menu_item {
  height: 3em;
  line-height: 3em;
}

.menu_item a {
  display: block;
  background: #3498db;
  color: #fff;
  border-right: 0.25em solid #fff;
  padding-right: 2em;
  position: relative;
  overflow: hidden;
  z-index: 1;
}

.menu_item a:before {
  content: '';
  position: absolute;
  left: -100%;
  top: 0;
  bottom: 0;
  right: 100%;
  background: #2980d9;
  transition: 0.35s;
  z-index: -1;
}

@media screen and(min-width: 55rem) {
  .menu_item a:hover:before {
    left: 0;
    right: 0;
  }

  .menu_item a:hover .fa {
    font-size: 1.25em;
    width: 3.6em;
  }
}

@media screen and(max-width: 55rem) {
  .menu_item span {
    /* margin-left: 1em; */
    width: 0;
    transition: 0.5s ease;
  }

  .menu_item a:hover span {
    margin-left: 3.5em;
    width: auto;
  }
}

.menu_item:last-child a {
  border-right: 0;
}

.menu_item .fa {
  background: #2980d9;
  width: 3em;
  line-height:inherit;
  text-align: center;
  height: 100%; // i tag 요소가 공간을 차지할때 높이가 맞지 않는다.
  position: absolute; // fa가 절댓값으로 붕 뜨데, 부모의 height가 100%다 쓴다.
  left: 0;
  transition: 0.35s;
}

.menu_item span {
  margin-left: 3.5em;
  display: block;
}
```
</details>

[[ Nav Style - part2 ] 반응형 메뉴 스타일 구현하기(모바일 구간) - flex, fontawesome, 반응형, 클릭 메뉴 구현](https://www.youtube.com/watch?v=EbhJv2CYXXA&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=46)

<details>
    <summary>menu animation</summary>

```css
.wrapper {
  max-width: 60rem;
  width: 100%;
  margin: 5rem auto;
  position: relative;
}

a {
  text-decoration: none;
}

nav {
  display: flex;
  justify-content: center;
  font-size: 1.2em;
}

.menu_item {
  height: 3em;
  line-height: 3em;
}

.menu_item a {
  display: block;
  background: #3498db;
  color: #fff;
  border-right: 0.25em solid #fff;
  padding-right: 2em;
  position: relative;
  overflow: hidden;
  z-index: 1;
}

.menu_item a:before {
  content: '';
  position: absolute;
  left: -100%;
  top: 0;
  bottom: 0;
  right: 100%;
  background: #2980d9;
  transition: 0.35s;
  z-index: -1;
}

@media screen and(min-width: 55rem) {
  .menu_item a:hover:before {
    left: 0;
    right: 0;
  }

  .menu_item a:hover .fa {
    font-size: 1.25em;
    width: 3.6em;
  }
}

.open_menu,
.burger {
  display: none;
}

@media screen and(max-width: 55rem) {
  .menu_item span {
    /* margin-left: 1em; */
    width: 0;
    transition: 0.5s ease;
  }

  .menu_item a:hover span {
    margin-left: 3.5em;
    width: auto;
  }
}

@media screen and(max-width: 30rem) {
  .burger {
    display: block;
    width: 3em;
    height: 3em;
    background: #3498db;
    color: #fff;
    text-align: center;
    line-height: 3em;
    margin-bottom: 0.25em;
    cursor: pointer;
    transition: background 0.35s;
  }

  .open_menu:checked+.burger {
    background: #2980d9;
  }

  .open_menu:checked+.burger+nav {
    left: 0;
    right: 0;
  }

  nav {
    flex-direction: column;
    position: absolute;
    width: 100%;
    left: -100%;
    right: 100%;
    transition: 0.35s;
  }

  .menu_item {
    border-bottom: 0.25em solid #fff;
    box-sizing: content-box;
  }

  .menu_item a {
    border-right: 0;
  }

  .menu_item a:hover:before {
    left: 0;
    right: 0;
  }

  .menu_item a:hover .fa {
    font-size: 1.25em;
    width: 3.6em;
  }

  .menu_item span {
    margin-left: 3.5em;
  }
}

.menu_item:last-child a {
  border-right: 0;
}

.menu_item .fa {
  background: #2980d9;
  width: 3em;
  line-height: inherit;
  text-align: center;
  height: 100%;
  position: absolute;
  left: 0;
  transition: 0.35s;
}

.menu_item span {
  margin-left: 3.5em;
  display: block;
}
```
</details>

[[ Tooltip ] 말풍선 툴팁 애니메이션, animation, tooltip,](https://www.youtube.com/watch?v=UOda4Gw1Piw&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=47)

<details>
    <summary>tooltip animation & target css</summary>

```css
.wrapper {
  max-width: 50rem;
  width: 100%;
  margin: 2rem auto;
  padding: 5rem;
  background: #fff;
  border: 0.5rem solid #34495e;
}

.tooltip {
  position: relative;
  display: inline-block;
}

.tip {
  position: absolute;
  left: 100%;
  top: 50%;
  padding: 1em;
  font-size: 0.8em;
  background: #34495e;
  border-radius: 1em;
  color: #fff;
  white-space: nowrap;
  transform: translateY(-50%);
  opacity: 0;
  transition: 0.35s;
  margin-left: 1rem;
}

.tooltip:hover .tip {
  opacity: 1;
  margin-left: 0;
}

.tip:before {
  content: '';
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0.5rem;
  border-color: transparent #34495e transparent transparent;
  position: absolute;
  right: 100%;
  top: 50%;
  transform: translateY(-50%);
}

#footnote:target {
  background: black;
  color: red;
}
```
</details>

[[ Cube rotation 1 ] transform을 활용한 cube 3D 애니메이션 구현하기 파트 1 - 정육면체 만들기](https://www.youtube.com/watch?v=JotTaIxFn-A&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=51)
[[ Cube rotation 2 ] transform을 활용한 cube 3D 애니메이션 구현하기 파트 2 - 버튼으로 컨트롤하기](https://www.youtube.com/watch?v=g9dEtaug9Uo&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=52)

<details>
    <summary>perspective, perspective-origin, transform animation</summary>

```css
.wrapper {
  max-width: 50rem;
  width: 100%;
  margin: 1rem auto;
  text-align: center;
}

.perspective {
  perspective: 2000px;
  position: relative;
  perspective-origin: 25rem -150px;
}

.cube {
  position: relative;
  width: 400px;
  margin: 3.5rem auto;
  transition: 0.5s;
  transform-style: preserve-3d;
}

.cube div {
  position: absolute;
  width: 400px;
  height: 400px;
  opacity: 0.95;
}

.cube div img {
  width: 100%;
  height: 100%;
}

.front {
  transform: translateZ(200px);
}

.back {
  transform: translateZ(-200px) rotateY(180deg);
}

.left {
  transform: rotateY(-90deg) translateZ(200px);
}

.right {
  transform: rotateY(90deg) translateZ(200px);
}

.top {
  transform: rotateX(90deg) translateZ(200px);
}

.bottom {
  transform: rotateX(-90deg) translateZ(200px);
}

input {
  display: none;
}

#rotate:checked~.cube {
  animation: rotate 10s infinite linear;
}

@keyframes rotate {
  0% {
    transform: rotateY(0deg);
  }

  100% {
    transform: rotateY(360deg);
  }
}


#font:checked~.cube {
  animation: none;
  transform: none;
}

#back:checked~.cube {
  animation: none;
  transform: rotateY(180deg);
}

#right:checked~.cube {
  animation: none;
  transform: rotateY(-90deg);
}

#left:checked~.cube {
  animation: none;
  transform: rotateY(90deg);
}

#top:checked~.cube {
  animation: none;
  transform: rotateX(-90deg);
}

#bottom:checked~.cube {
  animation: none;
  transform: rotateX(90deg);
}

label {
  display: inline-block;
  padding: 0.25em 0.5em;
  border-radius: 0.5rem;
  background: #2980b9;
  color: #fff;
  margin: 0 0.25rem;
  transition: 0.25s;
}

input:checked+label {
  background: #3498db;
}
```
</details>

[[3D animation 1 ] Link Animation, 3D 마우스를 올리면 위로 올라가는 링크 애니메이션](https://www.youtube.com/watch?v=TyII352mVQI&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=73)
[[3D animation 2 ] Link Animation, 3D 마우스를 올리면 위로 살짝 들리는 링크 애니메이션](https://www.youtube.com/watch?v=FWh7kgTziqM&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=73)

[[ 버튼 애니메이션 ] Button Animation, 마우스를 올리면 아이콘과 글씨가 나타나는 애니메이션](https://www.youtube.com/watch?v=dzTf4RrD14I&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=75)

[[ 카드 뒤집기 ] Card rotate - 마우스를 올리면 뒤집히는 카드 구현하기, transform, 1000명 구독 기념 이벤트 몸 공개!](https://www.youtube.com/watch?v=IsjwJjphqdo&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=63)

  - backface-visibility
  - transform-style: flat | preserve-3d

 [[ 플렉스 애니메이션 ] flex css animation, 줄무늬 메뉴 구현하기](https://www.youtube.com/watch?v=8mvb5L6VXbk&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=66)

[CSS3 - 84 [ CSS ANIMATION ] 토글 슬라이드 버튼 애니메이션, form, flex, position, transition, css3 animation](https://www.youtube.com/watch?v=uYwKQYzRLc0&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=85)

 [CSS3 - 85 [ CSS ANIMATION ] 공지 카드 애니메이션, card notification css animation](https://www.youtube.com/watch?v=HJG2MuosALk&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=86)

 [CSS3 - 117 [Form Animation] 폼입력을 빠르게, floating form, CSS로 구현하기](https://www.youtube.com/watch?v=c8_WfifwqUk&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=129)
  - :focus-within, ::placeholder

 [CSS3 - 93 [ Wipe Out Text Animation ] CSS로 글자가 채워지는 애니메이션 구현하기](https://www.youtube.com/watch?v=h6z9qYKOK0w&list=PL-qMANrofLyvQ6FuaIe3YRRX82eISDy11&index=95)
